### PR TITLE
Merges Issue#4 with main

### PR DESCRIPTION
**Pull request by oscarzhpersson**
Adds compilation functionality. The CI checks if all python files in the cloned repo can compile, returns error code accordingly (SUCCESS, ERROR)

### CODE REVIEW

**Comment by soderqw** [comment]
Code checks if all python files in the cloned repo can compile, it is easy to understand and looks good. I did however read through the assignment property for compilation again, and it looks like it says: 

_"... the CI server compiles the branch where the change has been made ..."_ 

I'm not sure if the code currently detects a branch and compiles that branch explicitly, maybe it does, and I'm not seeing it. Just wanted to point it out.

**Review by mustafamusse — APPROVED** [review]
+1

**Comment by oscarzhpersson** [comment]
Will change to "f'git clone -b {branch} {repo}'" in accordance to Tim's suggestion

**Review by soderqw — APPROVED** [review]
What i previously commented is resolved

**Pull request merged**
